project:
  type: book
  output-dir: docs

book:
  title: "Data Literacy"
  author: "Brycen Boettcher"
  date: "12/8/2022"
  chapters:
    - index.qmd
    - narrative.qmd
    - narrative 2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    execute:
      echo:true
 

editor: visual

